### ISSUE TITLE
Primera retroalimentación

### ISSUE THREAD

**Issue by DrJoseGallardo** [DrMarcosMancilla/MarcosMancilla#1]
Estimado Marcos: Aquí te envio mi retroalimentación de tu trabajo.

1.- Planteamiento del problema: Muy buena redacción. Favor especificar a que te refieres con "presentan un desempeño productivo acorde con lo esperado." Trata de ser más específico en relación a la variable respuesta y a la variable predictora. 

2.- En la descripción de los datos ser más claro  con esta frase "presencia de marcadores o QTL para SRS" quizás debe decir ... para resistencia a SRS.

3.- En la descripción de los datos, favor incluir el numero total de observaciones. Identificar claramente la variable respuesta o de interes y las variables de clasificación o factor que deseas evaluar. Si hay mas de una indicar cual es la mas importante. También recomiendo identificar si las variables son continuas o discretas.

4.- Observaciones al reporte: a) Comentar los bloques de código con #. b) Transformar las variables a factor antes de realizar boxplot. c) Realizar boxplot de la variable respuesta en funcion de las variables de los factores. d) Los histogramas no deben tener tantas clases, sugiero entre 8 y 15.

5.- Me pierdo un poco con tu interes de analizar biomasa. Esperas que la mortalidad en SRS influya en biomasa?

Saludos

**Comment by DrMarcosMancilla** [comment]
Muchas gracias por los comentarios, Prof. Gallardo. Acabo de subir versión modificada del archivo "Readme" según las recomendaciones. 
En cuanto al punto 4, hice ajuste de histogramas que me gustaría revise. Además, tengo una duda en la transformación de variables a factor como lo sugiere: hice el ajuste para la variable "Mortalidad" y corrí código, pero el resultado fue que la caja se transformó en línea. Necesito feedback en este punto para continuar.
Del punto 5, tiene razón. De acuerdo al problema planteado, la variable respuesta es la mortalidad asociada a SRS.
Saludos

**Comment by DrMarcosMancilla** [comment]
Prof. Gallardo: Se actualizó versión anterior. Se arreglaron elementos de formato, títulos y comentarios al texto. También se dejaron fuera las líneas de código.

**Comment by DrJoseGallardo** [comment]
Estimado Marcos, 

Se ve mucho mejor el reporte, te sugiero no incluir el argumento **fill** en los histogramas, ver lineas 56 y similares

ggplot(dat, aes(x = Biomasa_kg, fill=Subgrupo)) +
  geom_histogram(bins = 30)

Para eso es mejor boxplot, como ya tienes en tu código.

Finalmente, la variable mortalidad no es factor.

Saludos
